// <auto-generated />
namespace DealDouble.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.0-preview2-24180-01")]
    public sealed partial class update_Endingtime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Endingtime));
        
        string IMigrationMetadata.Id
        {
            get { return "202405240555278_update_Endingtime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
